import type { HistoricAward } from "./types";

export const HISTORIC_AWARDS: HistoricAward[] = [
  {
    programCode: "SS4A",
    projectName: "Wilmington High-Injury Network Intersection Safety",
    category: "safety",
    tags: ["intersection", "pedestrian", "signal", "high-crash", "equity"],
    year: 2023,
    outcome: "awarded",
    notes: "SS4A Implementation Grant — systemic urban intersection safety.",
  },
  {
    programCode: "SS4A",
    projectName: "Kent County Vulnerable Road User Safety Plan",
    category: "planning",
    tags: ["safety-plan", "vru", "data-driven", "equity"],
    year: 2022,
    outcome: "awarded",
    notes: "SS4A Action Plan Grant used as a model for later implementation.",
  },
  {
    programCode: "RAISE",
    projectName: "US 13 Corridor Complete Streets — Dover",
    category: "complete-streets",
    tags: ["complete-streets", "transit", "bike-ped", "equity", "economic-development"],
    year: 2021,
    outcome: "awarded",
    notes: "Multimodal corridor with strong community and safety benefits.",
  },
  {
    programCode: "INFRA",
    projectName: "I-95 / SR 1 Freight Reliability Improvements",
    category: "freight",
    tags: ["freight", "interstate", "bottleneck", "reliability"],
    year: 2020,
    outcome: "not-awarded",
    notes: "Strong freight case but weaker rural/equity narrative.",
  },
  {
    programCode: "BRIDGE",
    projectName: "Bridge Rehabilitation Group 2 — Nanticoke and Broadkill",
    category: "bridge",
    tags: ["bridge", "structurally-deficient", "rural", "load-posting"],
    year: 2023,
    outcome: "awarded",
    notes: "BIP formula/competitive hybrid — bundled rural bridges scored well.",
  },
  {
    programCode: "PROTECT",
    projectName: "SR 1 Coastal Resilience and Flood Mitigation",
    category: "resilience",
    tags: ["flood", "sea-level", "evacuation", "coastal", "resilience"],
    year: 2024,
    outcome: "awarded",
    notes: "Coastal evacuation route resilience aligned with PROTECT priorities.",
  },
  {
    programCode: "CFI",
    projectName: "US 13 Alternative Fuel Corridor Charging",
    category: "ev-charging",
    tags: ["ev", "corridor", "alternative-fuel", "rural"],
    year: 2023,
    outcome: "awarded",
    notes: "Corridor charging with rural coverage gaps filled.",
  },
  {
    programCode: "RAISE",
    projectName: "Statewide Pavement Preservation Package",
    category: "pavement",
    tags: ["pavement", "preservation", "state-of-good-repair"],
    year: 2022,
    outcome: "not-awarded",
    notes: "State of good repair alone was not competitive without equity/safety story.",
  },
];
